name: EAS Build
on:
  workflow_dispatch:
  pull_request_target:
    paths:
      - 'kryptolearn/**'
  push:
    branches:
      - main
    paths:
      - 'kryptolearn/**'

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kryptolearn
    steps:
      - uses: actions/checkout@v3
      - name: ls
        run: ls
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: kryptolearn/package-lock.json
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build on EAS
        run: eas build -p android --wait --non-interactive
